<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>Henrik Cooke</Authors>
        <Description>Postgres/Npgsql adapter for Cooke.Gnissel ORM.</Description>
        <Copyright>Cooke Software Solutions AB</Copyright>
        <PackageProjectUrl>https://github.com/Cooke/gnissel</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Company>Cooke Software Solutions AB</Company>
        <Version>0.13.0</Version>
        <LangVersion>latestmajor</LangVersion>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <RepositoryUrl>https://github.com/Cooke/gnissel</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>ORM, SQL, database, PostgreSQL, Npgsql</PackageTags>
        <PackageReleaseNotes>Version 0.13.0:
- Updated to match Cooke.Gnissel 0.13.0
- Runtime name providers support
- Improved expression-to-SQL translation</PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql" Version="8.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Cooke.Gnissel\Cooke.Gnissel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
